### ISSUE TITLE
Aborted (core dumped) on ViewMap object

### ISSUE THREAD

**Issue by afrigeri** [andrea-bistacchi/PZero#10]
1 - open LP_test.p0, from example dataset Llyn-Padarn
2 - open Map View
3 - Add image / RGB -> Ok!
4 - Add DEMs and DOM
5 - select jpeg image map

Traceback (most recent call last):
  File "/home/alf/gitwrk/PZero/pzero/windows_factory.py", line 867, in <lambda>
    property_texture_combo.currentIndexChanged.connect(lambda: self.toggle_property_texture())
  File "/home/alf/gitwrk/PZero/pzero/windows_factory.py", line 972, in toggle_property_texture
    self.plotter.remove_scalar_bar()
AttributeError: 'ViewMap' object has no attribute 'plotter'
Aborted (core dumped)

**Comment by andrea-bistacchi** [comment]
Thanks, we have to check this.

**Comment by andrea-bistacchi** [comment]
Hi, I am not sure if the fix proposed by @gbene works, since you can have more than one scalar bar when more than one object is shown with a property.

**Comment by gbene** [comment]
Yes. 
I've added the self.plotter.remove_scalar_bar() line (the original culprit of the crash) to avoid having displayed different scalarbars for the same object. This happened when switching between properties (eg. changing X to Y displayed both the X scalar bar and Y scalarbar). 
We could try and put another conditional in the if statement to check if the property change trigger comes from different objects or we could just comment out those line for now.

**Comment by afrigeri** [comment]
synced with the master.  Selecting the jpeg image map in map view (point 5 in the issue report above), now does not crash the program (great!).  A white frame appears (the boundary of the data frame).

<img width="1262" alt="image" src="https://user-images.githubusercontent.com/158104/166672609-fbafe62f-02e1-4964-9add-041015387dac.png">

**Comment by andrea-bistacchi** [comment]
Yes. You can show the image from the Image tree.

**Comment by afrigeri** [comment]
> Yes. You can show the image from the Image tree.

Oh yes, perfect!
