### ISSUE TITLE
[bug] XsPolyLine project to other X-section not working

### ISSUE THREAD

**Issue by andrea-bistacchi** [andrea-bistacchi/PZero#14]
Method [project_2_xs](https://github.com/andrea-bistacchi/PZero/blob/d8e5d17ee8b93e4a655940dd941d35b1f08d5916/pzero/three_d_surfaces.py#L1054) does not project XsPolyLine's.

This is because the lines doing the projection are [missing in the case for XsPolyLine's](https://github.com/andrea-bistacchi/PZero/blob/d8e5d17ee8b93e4a655940dd941d35b1f08d5916/pzero/three_d_surfaces.py#L1142) (while they are [present for PolyLine's and VertexSet's](https://github.com/andrea-bistacchi/PZero/blob/d8e5d17ee8b93e4a655940dd941d35b1f08d5916/pzero/three_d_surfaces.py#L1131)).

**Comment by andrea-bistacchi** [comment]
This should be the problem

![image](https://user-images.githubusercontent.com/12087912/216390074-18ad38e2-e711-47cd-9e29-5d5ea9bae5b9.png)

**Comment by gbene** [comment]
fixed in https://github.com/andrea-bistacchi/PZero/commit/45d3be3c1f57765cf6c64df5dc41c0171b9767d9
