### ISSUE TITLE
[bug] open new project with 3D window already opened

### ISSUE THREAD

**Issue by andrea-bistacchi** [andrea-bistacchi/PZero#16]
Opening a new project with a 3D window already opened freezes PZero.

**Comment by gbene** [comment]
Related to views and view properties not being cleared when a project is closed (without closing the main program)

**Comment by andrea-bistacchi** [comment]
This has been temporarily fixed with [commit 0a5803b1ec1f067e031ff44fedf797256305a13c](https://github.com/andrea-bistacchi/PZero/tree/0a5803b1ec1f067e031ff44fedf797256305a13c).

**Comment by mcbaguetti** [comment]
I think this was fixed and solved with the addition of deleteOnClose inside window_factory.py (commit [here](https://github.com/andrea-bistacchi/PZero/commit/9f160ecf02f123436da18c8f15efe82a4ddc5b5e))
