### ISSUE TITLE
Project to DEM

### ISSUE THREAD

**Issue by andrea-bistacchi** [andrea-bistacchi/PZero#24]
[vtkPointInterpolator2D](https://vtk.org/doc/nightly/html/classvtkPointInterpolator2D.html) seems more general than the current implementation. It interpolates from-to any vtkDataSet. To interpolate z values use boolean flag InterpolateZ. Different kernels are available and should be tested.

**Comment by gbene** [comment]
I've implemented it in https://github.com/andrea-bistacchi/PZero/commit/5871e0d10b4a6796ff6e2d890e9c8c6b2beed56d

**Comment by andrea-bistacchi** [comment]
Does it work from the DEM directly now? Or still from a DEM loaded as an image?

**Comment by andrea-bistacchi** [comment]
Great! Issue closed
