### ISSUE TITLE
home view in 3D view

### ISSUE THREAD

**Issue by andrea-bistacchi** [andrea-bistacchi/PZero#27]
Clicking on "go to home view" before recording it with "acquire home view" causes a crash. We must add some code to

(1) store an initial home view immediately after the first actors are shown;

(2) store a valid home view even if no actor is present in the view.

Alternatively add a "try" - "except" to avoid the crash.

**Comment by gbene** [comment]
This is strange I do not have this problem. Can you please share the crash message. Do you have the latest push? I have already added a try - except in https://github.com/andrea-bistacchi/PZero/commit/ec69bda6f42fcbc93b6325d399e0b940ec4e2ced#diff-ac6f2763d1895cb12998ff07ccea935b43398906887696f83c4819dab54dd205R3343

**Comment by andrea-bistacchi** [comment]
OK, this was a bug from last week. Thanks! Closed
