### ISSUE TITLE
Vertical exaggeration

### ISSUE THREAD

**Issue by andrea-bistacchi** [andrea-bistacchi/PZero#32]
Vertical scale in 3D view can be different with respect to map scale, e,g. to obtain vertical exaggeration.

This is set with the **set_scale** method of the **PyVista Plotter**.

See example in https://github.com/pyvista/pyvista-support/issues/8#issuecomment-492908599

```
p = pv.Plotter()
p.add_mesh(gravi, **gargs)
p.add_mesh(surf)
p.set_scale(zscale=scale_factor)
p.camera_position = [2,1,0.2]
p.show()
```

**Comment by gbene** [comment]
I think there is a duplicate issue #21

**Comment by andrea-bistacchi** [comment]
Yes, I closed https://github.com/andrea-bistacchi/PZero/issues/21#issue-1560776425.

It appears that **set_scale** could be applied to both **PyVista** **Plotter** or **Renderer**.

**Comment by gbene** [comment]
I think that they are the same function but the plotter route was added to be more accessible (**plotter.set_scale()** vs **plotter.renderer.set_scale()**). I have tested it and it seems that they work in the same way.

**Comment by gbene** [comment]
Added in https://github.com/andrea-bistacchi/PZero/commit/92311e816ce3a452cae2f67f2b818c175e7fedf0
