### ISSUE TITLE
Incoherent naming objects for the section intersection and DEM projection function

### ISSUE THREAD

**Issue by gbene** [andrea-bistacchi/PZero#36]
The section intersection function creates entities **without** the section name in the name (entity1_intersection). The function should be modified to be more coherent with the projection naming scheme (resulting in for example entity1_intersection_**section_name**).

**Comment by andrea-bistacchi** [comment]
OK, maybe we can make it shorter as in **entity1_int_section_name**.

**Comment by gbene** [comment]
Ok. I noticed the same problem for the projection to DEMs. We could name such entities as **entity1_projected_DEM**.

**Comment by andrea-bistacchi** [comment]
I suggest the shorter **entity1_proj_DEM**

**Comment by gbene** [comment]
Solved in https://github.com/andrea-bistacchi/PZero/commit/11b23fc82a42d370c4e35557dc685cbaa09ffb96
