### ISSUE TITLE
crash when editing geological type

### ISSUE THREAD

**Issue by andrea-bistacchi** [andrea-bistacchi/PZero#52]
We have a bug. When the geological type is edited in the geological collection table, PZero crashes. This used to work flawlessly.

I suspect we have a problem with a signal related to changing an entity metadata.

I'll try to figure out.

**Comment by mcbaguetti** [comment]
I pushed the solution on the [env_testing](https://github.com/andrea-bistacchi/PZero/tree/env_testing) branch

**Comment by mcbaguetti** [comment]
pushed on the main branch with this [commit](https://github.com/andrea-bistacchi/PZero/commit/9f160ecf02f123436da18c8f15efe82a4ddc5b5e#diff-59f0179f5140d5c6c6cb8ed8dfb0170c3586caecc1a0f527533795a040007a0a) inside legend_manager.py
